# Generated by Django 4.2 on 2023-05-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=150)),
                ('data_de_nnascimento', models.DateField()),
            ],
        ),
    ]
