# Generated by Django 4.2 on 2023-05-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_usuario',
            old_name='data_de_nnascimento',
            new_name='data_de_nascimento',
        ),
    ]
