# Generated by Django 4.2 on 2023-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cadastro_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
