# Generated by Django 4.2.1 on 2023-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cadastro_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='anuncios_tbl',
            fields=[
                ('id_anuncio', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
            ],
        ),
    ]
